---
title: "Zestaw 16"
lang: pl
output:
  word_document: default
  pdf_document: default
---


1. W folderze Debug16 znajduje się projekt z kodem w języku C. W pliku main.c w niektórych linijkach są komentarze. Twoim zadaniem jest wpisanie wartości odpowiednich zmiennych po wykonaniu konkretnej linii kodu.

*Punktacja: 1 pkt za każdą poprawną linijkę, łącznie 7 pkt.*

2. W folderze Popraw16 znajduje się kod w języku C, który nie spełnia zasad kompilacji. Popraw kod modyfikując dokładnie 1 linijkę tak, aby się kompilował. Zabronioną operacją jest komentowanie kodu. Do zmodyfikowanych linii zaliczają się zarówno linie istotne ze względu na kompilację jak i te nieistotne (np. dodanie spacji przed operatorem może być operacją nieistotną ze względu na kompilację, ale będzie liczone jako zmodyfikowana linijka).

*Punktacja: 7 pkt.*

3. Napisz funkcję, która jako argument otrzymuje dodatnią liczbę całkowitą $n$ i zwraca liczbę równą sumę sześcianów kolejnych liczb naturalnych dodatnich mniejszych lub równych $n$ ($1^3+2^3+\ldots+n^3$). Nie korzystaj z żadnych gotowych funkcji bibliotecznych ani wbudowanych. Stwórz dwa przypadki testowe dla funkcji.

Przypadki testowe:

| $n$ | wyjście|
|---|---|
| 1 | 1 |
| 2 | 9 |
| 3 | 36 |

*Punktacja: 8 pkt.*

4. Napisz funkcję, która otrzymuje trzy argumenty:  dwa wskaźniki na funkcje o jednym argumencie typu `int` zwracające wartość typu `int` oraz wartość $n$ typu `int`. Funkcja zwraca 2 jeśli jeżeli otrzymane w argumentach funkcje są równe dla wartości parzystych dodatnich mniejszych niż $n$ są równe i zwraca 0 w przeciwnym wypadku. 

*Punktacja: 8 pkt.*

5. Napisz funkcję rekurencyjną, która dla otrzymanej w argumencie nieujemnej liczby całkowitej $n$ zwraca
wartość elementu o indeksie $n$ ciągu zdefiniowanego w następujący sposób

$$a_0=a_1=2$$

$$a_{2n}=a_n+1$$
$$a_{2n+1}=a_{2n}-1$$
Stwórz dwa przypadki testowe dla funkcji.

Przypadki testowe:

| $n$ | $a_n$ |
|---|---|
| 2 |3 |
| 3 | 2 |
| 4 | 4 |
| 5 | 3 |

*Punktacja: 10 pkt.*

6. Napisz program, w których stworzysz tablicę o 25 elementach typu `int`. Następnie za pomocą samodzielnie napisanej funkcji uzupełnij tablicę kolejnymi wyrazami ciągu Fibonacciego. Zadanie może używać kilku samodzielnie napisanych funkcji, ale nie może używać funkcji wbudowanych czy bibliotecznych.

Wskazówka: informacje pomocnicze https://pl.wikipedia.org/wiki/Ci%C4%85g_Fibonacciego

*Punktacja: 10 pkt.*
